export const MenuItems = [
    {
        id:1,
        itemID:"degan01",
        name:"Degan",
        imgSrc:"https://selangor.bazaar-rakyat.com/wp-content/uploads/2020/04/kindpng_5759450.png"
    },
    {
        id:2,
        itemID:"manggis01",
        name:"Manggis",
        imgSrc:"https://www.pngpix.com/wp-content/uploads/2016/03/Purple-Mangosteen-PNG-Image3-500x418.png"
    },
    {
        id:3,
        itemID:"cola01",
        name:"Coca-Cola",
        imgSrc:"https://www.pngarts.com/files/3/Coca-Cola-Transparent-Image.png"
    }
]

export const Items = [
    {
        id:1,
        itemID:"degan01",
        name:"Degan",
        imgSrc:"https://selangor.bazaar-rakyat.com/wp-content/uploads/2020/04/kindpng_5759450.png",
        rating:4,
        price:"20000"
    },
    {
        id:2,
        itemID:"manggis01",
        name:"Manggis",
        imgSrc:"https://www.pngpix.com/wp-content/uploads/2016/03/Purple-Mangosteen-PNG-Image3-500x418.png",
        rating:4,
        price:"20000"
    },
    {
        id:3,
        itemID:"cola01",
        name:"Coca-Cola",
        imgSrc:"https://www.pngarts.com/files/3/Coca-Cola-Transparent-Image.png",
        rating:4,
        price:"20000"
    },
    {
        id:4,
        itemID:"degan01",
        name:"Degan",
        imgSrc:"https://selangor.bazaar-rakyat.com/wp-content/uploads/2020/04/kindpng_5759450.png",
        rating:4,
        price:"20000"
    },
    {
        id:5,
        itemID:"manggis01",
        name:"Manggis",
        imgSrc:"https://www.pngpix.com/wp-content/uploads/2016/03/Purple-Mangosteen-PNG-Image3-500x418.png",
        rating:4,
        price:"20000"
    },
    {
        id:6,
        itemID:"cola01",
        name:"Coca-Cola",
        imgSrc:"https://www.pngarts.com/files/3/Coca-Cola-Transparent-Image.png",
        rating:4,
        price:"20000"
    }
]